# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_auto_20170331_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(default='', help_text='Sigla do estado ou província', max_length=2, verbose_name='Sigla do estado ou província'),
            preserve_default=False,
        ),
    ]
