# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0003_state_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(blank=True, help_text='Informe apenas se o CEP for por endereço(CEP da casa ou prédio)', max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, help_text='\n            Informações adicionais sobre o endereço, exemplo:\n            Próximo aos correios\n        ', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.ForeignKey(help_text='Selecione ou cadastre um novo bairro', on_delete=django.db.models.deletion.CASCADE, to='adresses.Neighborhood', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(help_text='Número da casa/prédio', max_length=7, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Nome da rua/avenida/viela', max_length=200, verbose_name='Rua/avenida/viela/praça'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Informe o nome da cidade', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(help_text='Selecione ou cadastre o estado/província desta cidade', on_delete=django.db.models.deletion.CASCADE, to='adresses.State', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Informe o nome deste país', max_length=150, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(help_text='Selecione ou cadastre a cidade deste bairro', on_delete=django.db.models.deletion.CASCADE, to='adresses.City', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(help_text='Nome do bairro', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Informe o nome da região', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(help_text='Selecione ou cadastre o País deste estado', on_delete=django.db.models.deletion.CASCADE, to='adresses.Country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(help_text='Informe o nome do estado', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='state',
            name='region',
            field=models.ForeignKey(help_text='Selecione ou cadastre a região do país esta este estado', on_delete=django.db.models.deletion.CASCADE, to='adresses.Region', verbose_name='Região'),
        ),
    ]
