# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda-feira'), ('3', 'Terça-feira'), ('4', 'Quarta-feira'), ('5', 'Quinta-feira'), ('6', 'Sexta'), ('7', 'Sábado')], max_length=1, verbose_name='Dia da semana')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_phrase', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='School Name')),
                ('logo_image', models.ImageField(blank=True, upload_to='schools', verbose_name='Upload o logo do seu computador')),
                ('address', models.CharField(db_index=True, help_text='Note que vc precisa colocar o endereco completo da escola', max_length=255, verbose_name='School Address')),
                ('youtube_channel_link', models.CharField(help_text='Set the link for yout youtube channel or video', max_length=255, verbose_name='Youtube Channel')),
                ('facebook_page', models.CharField(help_text='Facebook Page', max_length=255, verbose_name='Facebook Page')),
                ('website', models.CharField(help_text='Your website', max_length=255, verbose_name='WebSite')),
                ('instagram', models.CharField(help_text='Instagram profile', max_length=255, verbose_name='Instagram')),
                ('admin_email', models.EmailField(help_text='Email de contato da escola', max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Ex.: +55 11 91001 0101', max_length=18, null=True, verbose_name='telefone')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Registration Fee Price', max_digits=10, null=True, verbose_name='Registration Fee Price')),
                ('workbook', models.DecimalField(blank=True, decimal_places=2, help_text='HWorkbook Price', max_digits=10, null=True, verbose_name='Workbook Price')),
                ('refounds', models.DecimalField(blank=True, decimal_places=2, help_text='Refounds', max_digits=10, null=True, verbose_name='Redounds')),
                ('low_season', models.CharField(blank=True, help_text='Low season', max_length=400, null=True, verbose_name='Low season')),
                ('high_season', models.CharField(blank=True, help_text='High season', max_length=400, null=True, verbose_name='High season')),
                ('embeded_map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.AddField(
            model_name='imagegalery',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='eventsoffered',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
