# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 21:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_beakfest_included', models.BooleanField(default=False, help_text='Is BreakFest Included?', verbose_name='Is BreakFeast included?')),
                ('is_lunch_included', models.BooleanField(default=False, help_text='Is lunch Included?', verbose_name='Is Lunch included?')),
                ('is_dinner_included', models.BooleanField(default=False, help_text='Is dinner Included?', verbose_name='Is Dinner Included?')),
                ('is_tv_in_the_bedroom', models.BooleanField(default=False, help_text='Do you have a tv in the bedroom?', verbose_name='Do you have a tv in the bedroom?')),
                ('is_wardrobe_in_the_bedroom', models.BooleanField(default=False, help_text='Do you have a wardrobe in the bedroom?', verbose_name='Do you have a wardrobe in the bedroom?')),
                ('is_air_in_the_badroom', models.BooleanField(default=False, help_text='Do you have a air conditioning in the bedroom?', verbose_name='Do you have a air conditioning in the bedroom?')),
                ('duration', models.CharField(help_text='Time of acomodation', max_length=255, verbose_name='Period of stay in')),
                ('wifi_free', models.BooleanField(default=False, help_text='Do you have free wifi?', verbose_name='Do you have free wifi?')),
                ('time_to_school', models.CharField(help_text='How much time it take from the school?', max_length=255, verbose_name='How much time it take from the school?')),
                ('differentials', models.CharField(help_text="What is your accomodation's differential", max_length=255, verbose_name='Tell Me about your differentials')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Course description', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=6)),
                ('visa_needed', models.BooleanField(help_text='Visa is needed?')),
                ('classes_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventsOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda-feira'), ('3', 'Terça-feira'), ('4', 'Quarta-feira'), ('5', 'Quinta-feira'), ('6', 'Sexta'), ('7', 'Sábado')], max_length=1, verbose_name='Dia da semana')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('initials', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_rating', models.CharField(choices=[('methodology', 'Metodologia'), ('staff', 'Atendimento'), ('structure', 'Estrutura'), ('coats', 'Custos')], max_length=15, verbose_name='Ratings')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='How many Stars Do you think this school diserve?')),
                ('comment', models.CharField(help_text='Why Would you like to do this rating?', max_length=255, verbose_name='Why this note?')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_phrase', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='School Name')),
                ('logo_image', models.ImageField(blank=True, upload_to='schools', verbose_name='Upload o logo do seu computador')),
                ('youtube_channel_link', models.CharField(help_text='Set the link for yout youtube channel or video', max_length=255, verbose_name='Youtube Channel')),
                ('facebook_page', models.CharField(help_text='Facebook Page', max_length=255, verbose_name='Facebook Page')),
                ('website', models.CharField(help_text='Your website', max_length=255, verbose_name='WebSite')),
                ('instagram', models.CharField(help_text='Instagram profile', max_length=255, verbose_name='Instagram')),
                ('admin_email', models.EmailField(help_text='Email de contato da escola', max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Ex.: +55 11 91001 0101', max_length=18, null=True, verbose_name='telefone')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Registration Fee Price', max_digits=10, null=True, verbose_name='Registration Fee Price')),
                ('workbook', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='HWorkbook Price', max_digits=10, null=True, verbose_name='Workbook Price')),
                ('refounds', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Refounds', max_digits=10, null=True, verbose_name='Redounds')),
                ('low_season', models.CharField(blank=True, help_text='Low season', max_length=400, null=True, verbose_name='Low season')),
                ('high_season', models.CharField(blank=True, help_text='High season', max_length=400, null=True, verbose_name='High season')),
                ('embeded_map', models.TextField()),
                ('accomodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Accommodation')),
                ('address', models.ForeignKey(help_text='Informe o endereço da escola', on_delete=django.db.models.deletion.CASCADE, to='adresses.Address')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embeded_code', models.TextField(default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='imagegalery',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='eventsoffered',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set([('school', 'user', 'type_of_rating')]),
        ),
    ]
