# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20170328_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acomodation',
            new_name='Accommodation',
        ),
    ]
