# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='school',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Languages'),
            preserve_default=False,
        ),
    ]
