# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20170329_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.ForeignKey(help_text='Informe o endereço da escola', on_delete=django.db.models.deletion.CASCADE, to='adresses.Address'),
        ),
    ]
