# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20170408_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='language',
            field=models.CharField(choices=[('PT-BR', 'BRAZILIAN PORTUGUESE'), ('PT-PT', 'PORTUGAL PORTUGUESE'), ('SP', 'SPANISH'), ('EN', 'ENGLISH'), ('FR', 'FRANCH'), ('IT', 'ITALIAN'), ('DT', 'DUTCH'), ('GM', 'GERAN')], default='EN', max_length=2),
            preserve_default=False,
        ),
    ]
