# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20170408_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('initials', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='language',
            field=models.CharField(choices=[('PT-BR', 'BRAZILIAN PORTUGUESE'), ('PT-PT', 'PORTUGAL PORTUGUESE'), ('SP', 'SPANISH'), ('EN', 'ENGLISH'), ('FR', 'FRENCH'), ('IT', 'ITALIAN'), ('DT', 'DUTCH'), ('GM', 'GERMAN')], max_length=2),
        ),
    ]
