# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20170409_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Languages'),
        ),
    ]
