# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_profile_birth_day'),
        ('schools', '0009_auto_20170409_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_rating', models.CharField(choices=[('methodology', 'Metodologia'), ('staff', 'Atendimento'), ('structure', 'Estrutura'), ('coats', 'Custos')], max_length=15, verbose_name='Ratings')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='How many Stars Do you think this school diserve?')),
                ('comment', models.CharField(help_text='Why Would you like to do this rating?', max_length=255, verbose_name='Why this note?')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set([('school', 'user', 'type_of_rating')]),
        ),
    ]
