# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20170409_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Course description', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=6)),
                ('visa_needed', models.BooleanField(help_text='Visa is needed?')),
                ('classes_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
